/*
 * App: Character Generator
 * Author: Lucas Schoenardie
 * Created on: 20/10/2016
 * Description: Generates a D&D character with random stats and random name;
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace COMP1004_F2016_Mid_Term_Exam_2003221971
{
    public partial class GenerateNameForm : Form
    {
        public RaceAndClassForm previousForm;
        // private Instance Object
        private Random _random;

        public GenerateNameForm()
        {
            InitializeComponent();
        }

        private void GenerateNameForm_Load(object sender, EventArgs e)
        {
            // generate name on first form load
            if (Program.character.FirstName == null)
            {
                GenerateName();
            }
            else
            {
                FirstNameTextBox.Text = Program.character.FirstName;
                LastNameTextBox.Text = Program.character.LastName;
            }
           
        }

        private void BackButton_Click(object sender, EventArgs e)
        {
           
            // Show the parent form
            this.previousForm.Show();

            // Close this form
            this.Close();
        }

        private void NextButton_Click(object sender, EventArgs e)
        {
            // Make sure names were generated
            if(FirstNameTextBox.Text == "")
            {
                MessageBox.Show("Please, generate name first");
            }
            else
            {
                // Instantiate final form
                FinalForm finalForm = new FinalForm();
                finalForm.previousForm = this;

                // Show final form and hide this one
                finalForm.Show();
                this.Hide();
            }
                        
        }

        // generate name 
        private void GenerateName()
        {
            _random = new Random(); // instantiate Random object           

            int generatedNumber = this._random.Next(Convert.ToInt32(this.FirstNamesListBox.Items.Count)); // generate number between 0 and (items collection size - 1)
            FirstNameTextBox.Text = FirstNamesListBox.Items[generatedNumber].ToString(); // get item from index generated by Random generator, convert to string and display in text box
            Program.character.FirstName = FirstNameTextBox.Text; // assing text box text to corresponding variable in character class
            generatedNumber = this._random.Next(Convert.ToInt32(this.LastNamesListBox.Items.Count));
            LastNameTextBox.Text = LastNamesListBox.Items[generatedNumber].ToString();
            Program.character.LastName = LastNameTextBox.Text;
        }

        // Calls generate name
        private void GenerateButton_Click(object sender, EventArgs e)
        {
            GenerateName();
        }
    }
}
